home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('',views.HomePageView.as_view(),name='home'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/',views.OrderCreateView.as_view(),name='create'),
    path('detail/<int:order_id>/',views.OrderDetailView.as_view(),name='detail'),
    path('cart/',views.CartView.as_view(),name='cart'),
    path('add_cart/<int:product_id>/',views.AddCartView.as_view(),name='add_to_cart'),
    path('remove/<int:product_id>/',views.RemoveProductCartView.as_view(),name='remove_product')
]

shop_boutique/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('products/',include('products.urls',namespace='products')),
    path('orders/',include('orders.urls',namespace='orders')),
    path('about/',include('about.urls',namespace='about'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from accounts.models import User
from products.models import Product
from django.core.validators import MinValueValidator,MaxValueValidator


class Order(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='order')
    paid = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    discount = models.PositiveSmallIntegerField(blank=True,null=True,default=0)

    class Meta:
        ordering = ('paid','created')

    def __str__(self):
        return str(self.id)

    def get_total_not_discount(self):
        return sum(item.get_cost() for item in self.items.all() )

    def get_total_price(self):
        total = sum(item.get_cost() for item in self.items.all() )
        if self.discount:
            discount_price = int((self.discount / 100) * total)
            return total - discount_price
        return total

    def discount_price(self):
        total = sum(item.get_cost() for item in self.items.all())
        if self.discount:
            discount_price = int((self.discount / 100) * total)
            return discount_price
        return 0


class OrderItem(models.Model):
    order = models.ForeignKey(Order,on_delete=models.CASCADE,related_name='items')
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    price = models.IntegerField()
    quantity = models.PositiveSmallIntegerField()

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.quantity * self.price


class Coupon(models.Model):
    code = models.CharField(max_length=30,unique=True)
    valid_from = models.DateTimeField()
    valid_to = models.DateTimeField()
    is_active = models.BooleanField(default=True)
    discount = models.PositiveSmallIntegerField(validators=(MinValueValidator(0),MaxValueValidator(90)))

    def __str__(self):
        return self.code

orders/forms.py
from django import forms


class CouponForm(forms.Form):
    code = forms.CharField(label='Code Discount',widget=forms.TextInput(attrs={'class':'form-control'}))

orders/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views import View
from .cart import Cart
from products.forms import QuantityForm
from products.models import Product
from django.contrib import messages
from .models import Order,OrderItem,Coupon
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CouponForm
from datetime import datetime
import pytz
import requests
from django.conf import settings
import json


class CartView(View):

    def get(self,request):
        products = Cart(request)
        return render(request,'orders/cart.html',{'products':products})


class AddCartView(View):

    def post(self,request,product_id):
        cart = Cart(request)
        product = get_object_or_404(Product,id=product_id)
        form = QuantityForm(request.POST)
        if form.is_valid():
            cart.add(form.cleaned_data['quantity'],product)
            messages.success(request,'The product added to cart.','success')
            return redirect('orders:cart')


class RemoveProductCartView(View):

    def get(self,request,product_id):
        cart = Cart(request)
        product = get_object_or_404(Product,id=product_id)
        cart.remove(product)
        messages.success(request,'The product deleted from your cart','success')
        return redirect('orders:cart')


class OrderCreateView(LoginRequiredMixin,View):

    def get(self,request):
        cart = Cart(request)
        order = Order.objects.create(user=request.user)
        for item in cart:
            OrderItem.objects.create(order=order,product=item['product'],price=item['price'],quantity=item['quantity'])
        return redirect('orders:detail',order.id)


class OrderDetailView(LoginRequiredMixin,View):
    form_class = CouponForm

    def get(self,request,order_id):
        cart = Cart(request)
        order = get_object_or_404(Order,id=order_id)
        return render(request, 'orders/checkout.html', {
            'order':order,'cart':cart,'form':self.form_class
        })

    def post(self,request,*args,**kwargs):
        order = get_object_or_404(Order,id=kwargs['order_id'])
        form = self.form_class(request.POST)
        now = datetime.now(tz=pytz.timezone('Asia/Tehran'))
        if form.is_valid():
            try:
                coupon = Coupon.objects.get(code__exact=form.cleaned_data['code'],valid_from__lte=now,
                                   valid_to__gte=now,is_active=True)
            except Coupon.DoesNotExist:
                messages.error(request,'The entered code is not correct','danger')
                return redirect('orders:detail',order.id)
            order.discount = coupon.discount
            order.save()
            messages.success(request,'The entered code has been applied','success')
            return redirect('orders:detail',order.id)


# ZarinPal settings
if settings.SANDBOX:
    sandbox = 'sandbox'
else:
    sandbox = 'www'

ZP_API_REQUEST = f"https://{sandbox}.zarinpal.com/pg/rest/WebGate/PaymentRequest.json"
ZP_API_VERIFY = f"https://{sandbox}.zarinpal.com/pg/rest/WebGate/PaymentVerification.json"
ZP_API_STARTPAY = f"https://{sandbox}.zarinpal.com/pg/StartPay/"

amount = 1000  # Rial / Required
description = "توضیحات مربوط به تراکنش را در این قسمت وارد کنید"  # Required
phone = 'YOUR_PHONE_NUMBER'  # Optional
# Important: need to edit for realy server.
CallbackURL = 'http://127.0.0.1:8000/verify/'


class OrderPayView(View):

    def get(self,request,order_id):
        order = get_object_or_404(Order,id=order_id)
        request.session['order_pay'] = {
            'order_id':order.id,
        }
        data = {
            "MerchantID": settings.MERCHANT,
            "Amount": order.get_total_price(),
            "Description": description,
            "Phone": phone,
            "CallbackURL": CallbackURL,
        }
        data = json.dumps(data)
        # set content length by data
        headers = {'content-type': 'application/json', 'content-length': str(len(data))}
        try:
            response = requests.post(ZP_API_REQUEST, data=data, headers=headers, timeout=10)

            if response.status_code == 200:
                response = response.json()
                if response['Status'] == 100:
                    return {'status': True, 'url': ZP_API_STARTPAY + str(response['Authority']),
                            'authority': response['Authority']}
                else:
                    return {'status': False, 'code': str(response['Status'])}
            return response

        except requests.exceptions.Timeout:
            return {'status': False, 'code': 'timeout'}
        except requests.exceptions.ConnectionError:
            return {'status': False, 'code': 'connection error'}


class OrderVerify(View):

    def get(self,request,authority):
        order_id = request.session['order_pay']['order_id']
        order = get_object_or_404(Order,id=order_id)
        data = {
            "MerchantID": settings.MERCHANT,
            "Amount": order.get_total_price(),
            "Authority": authority,
        }
        data = json.dumps(data)
        # set content length by data
        headers = {'content-type': 'application/json', 'content-length': str(len(data))}
        response = requests.post(ZP_API_VERIFY, data=data, headers=headers)

        if response.status_code == 200:
            response = response.json()
            if response['Status'] == 100:
                return {'status': True, 'RefID': response['RefID']}
            else:
                return {'status': False, 'code': str(response['Status'])}
        return response

orders/templates/orders/cart.html
{% extends 'base.html' %}

{% block content %}

    <!-- Start Top Search -->
    <div class="top-search">
        <div class="container">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-search"></i></span>
                <input type="text" class="form-control" placeholder="Search">
                <span class="input-group-addon close-search"><i class="fa fa-times"></i></span>
            </div>
        </div>
    </div>
    <!-- End Top Search -->

    <!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Cart</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active">Cart</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End All Title Box -->

    <!-- Start Cart  -->
    <div class="cart-box-main">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-main table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Images</th>
                                    <th>Product Name</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>Total</th>
                                    <th>Remove</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for product in products %}
                                <tr>
                                    <td class="thumbnail-img">
                                        <a href="#">
									<img class="img-fluid" src="{{ product.product.image.url}}" alt="" />
								        </a>
                                    </td>
                                    <td class="name-pr">
                                        <a href="#">
                                            {{ product.product.name }}
								        </a>
                                    </td>
                                    <td class="price-pr">
                                        <p>${{product.price }}</p>
                                    </td>
                                    <td class="quantity-box">{{ product.quantity }}</td>
                                    <td class="total-pr">
                                        <p>${{product.total_price }}</p>
                                    </td>
                                    <td class="remove-pr">
                                        <a href="{% url 'orders:remove_product' product.product.id %}">
									<i class="fas fa-times"></i>
								        </a>
                                    </td>


                                </tr>
                            {% endfor %}
                                <tr class="item">
                                    <td class="price-pr">
                                        Total
                                    </td>
                                    <td colspan="3"></td>
                                    <td>${{ products.get_total_price }}</td>
                                </tr>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>


            <a href="{% url 'orders:create' %}" class="ml-auto btn hvr-hover">Checkout</a>


        </div>
    </div>
    <!-- End Cart -->

    <!-- Start copyright  -->
    <div class="footer-copyright">
        <p class="footer-company">All Rights Reserved. &copy; 2018 <a href="#">ThewayShop</a> Design By :
            <a href="https://html.design/">html design</a></p>
    </div>
    <!-- End copyright  -->

    <a href="#" id="back-to-top" title="Back to top" style="display: none;">&uarr;</a>

{% endblock %}


orders/templates/orders/checkout.html
{% extends 'base.html' %}
{% block content %}


    <!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Checkout</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active">Checkout</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End All Title Box -->

    <!-- Start Cart  -->
    <div class="cart-box-main">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-lg-6 mb-3">
                    <div class="row">
                        </div>
                        <div class="col-md-12 col-lg-12">
                            <div class="odr-box">
                                <div class="title-left">
                                    <h3>Shopping cart</h3>
                                </div>
                                <div class="rounded p-2 bg-light">
                                    {% for item in cart %}
                                    <div class="media mb-2 border-bottom">
                                        <div class="media-body"> <a href="detail.html"> {{ item.product.name }}</a>
                                            <div class="small text-muted">Price: ${{ item.price }} <span class="mx-2">|</span> Qty:
                                                {{ item.quantity }} <span class="mx-2">|</span> Subtotal: ${{ item.total_price }}</div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12 col-lg-12">
                            <div class="order-box">
                                <div class="title-left">
                                    <h3>Your order</h3>
                                </div>
                                <div class="d-flex">
                                    <div class="font-weight-bold">Product</div>
                                    <div class="ml-auto font-weight-bold">Total</div>
                                </div>
                                <hr class="my-1">
                                <div class="d-flex">
                                    <h4>Sub Total</h4>
                                    <div class="ml-auto font-weight-bold"> $ {{ order.get_total_not_discount }} </div>
                                </div>
                                <div class="d-flex">
                                    <h4>Discount</h4>
                                    <div class="ml-auto font-weight-bold"> $ 40 </div>
                                </div>
                                <hr class="my-1">
                                <div class="d-flex">
                                    <h4>Coupon Discount</h4>
                                    <div class="ml-auto font-weight-bold"> % {{ order.discount }}</div>
                                </div>
                                <div class="d-flex">
                                    <h4>Tax</h4>
                                    <div class="ml-auto font-weight-bold"> $ {{ order.discount_price }} </div>
                                </div>
                                <hr>
                                <div class="d-flex gr-total">
                                    <h5>Grand Total</h5>
                                    <div class="ml-auto h5"> $ {{ order.get_total_price }} </div>
                                </div>
                                <hr> </div>
                                <br>
                            <form action="" method="post" class="col-md-4">
                                {% csrf_token %}
                                {{ form.as_table }}
                                <input type="submit" value="Apply" class="btn btn-outline-info" >
                            </form><br>
                            <a href="" class="btn btn-danger col-md-4">Pay</a>
                        </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Cart -->


{% endblock %}

orders/templates/orders/order1.html
{% extends 'base.html' %}
{% block content %}

    <h3>Checkout</h3>
    <p>Total: {{ order.get_total_price }}</p>
    <a href="" class="btn btn-danger">Pay</a>

{% endblock %}