home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('',views.HomePageView.as_view(),name='home'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/',views.OrderCreateView.as_view(),name='create'),
    path('detail/<int:order_id>/',views.OrderDetailView.as_view(),name='detail'),
    path('cart/',views.CartView.as_view(),name='cart'),
    path('add_cart/<int:product_id>/',views.AddCartView.as_view(),name='add_to_cart'),
    path('remove/<int:product_id>/',views.RemoveProductCartView.as_view(),name='remove_product')
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('detail/<int:product_id>/<slug:product_slug>/',views.ProductDetailView.as_view(),name='detail'),
    path('products_list/',views.ProductsView.as_view(),name='products_list'),
    path('products_list/category/<slug:category_slug>/',views.ProductsView.as_view(),name='category'),
]

shop_boutique/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('products/',include('products.urls',namespace='products')),
    path('orders/',include('orders.urls',namespace='orders')),
    path('about/',include('about.urls',namespace='about'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    sub_category = models.ForeignKey('self',on_delete=models.CASCADE,null=True,blank=True,related_name='category')
    is_sub = models.BooleanField(default=False)
    name = models.CharField(max_length=100)
    slug = models.SlugField()
    image = models.ImageField(blank=True,null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('products:category' , args=[self.slug])


class Product(models.Model):
    category = models.ManyToManyField(Category,related_name='products')
    name = models.CharField(max_length=150)
    slug = models.SlugField()
    image = models.ImageField()
    price = models.IntegerField()
    is_available = models.BooleanField(default=True)
    description = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.name} {self.is_available}'

products/forms.py
from django import forms


class QuantityForm(forms.Form):
    quantity = forms.IntegerField(min_value=0,widget=forms.NumberInput(attrs={'class':'form-control'}))

products/views.py
from django.shortcuts import render,get_object_or_404
from django.views.generic import DetailView,ListView
from .models import Product,Category
from django.views import View
from .forms import QuantityForm


class ProductDetailView(DetailView):
    template_name = 'products/detail.html'
    context_object_name = 'product'
    form_class = QuantityForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.form_class
        return context

    def get_object(self, queryset=None):
        return get_object_or_404(Product,id=self.kwargs['product_id'],slug=self.kwargs['product_slug'])


class ProductsView(View):

    def get(self,request, category_slug=None):
        products = Product.objects.filter(is_available=True)
        categories = Category.objects.filter(is_sub=False)
        if category_slug:
            category = get_object_or_404(Category,slug=category_slug)
            products = Product.objects.filter(category=category)
        return render(request,'products/products_list.html',{'products':products,'categories':categories})

products/templates/products/detail.html
{% extends 'base.html' %}
{% load static %}
{% block link %}
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet">
    <!-- CSS -->
    <link href="{% static 'css/product_detail.css' %}" rel="stylesheet">
    <meta name="robots" content="noindex,follow" />
{% endblock %}

{% block content %}
    <main class="container">

      <!-- Left Column / Headphones Image -->

        <img  src="{{ product.image.url }}" style="width: 300px;" alt="">



      <!-- Right Column -->
      <div class="right-column">

        <!-- Product Description -->
        <div class="product-description">
          <h1>{{ product.name }}</h1>
          <p>{{ product.description }}</p>
        </div>

        <!-- Product Configuration -->
        <div class="product-configuration">

            <!-- Product Pricing -->
            <div class="product-price">
              <span>148$</span>
            </div>
        </div>
      </div>
    </main>
    <br><br>
    <form action="{% url 'orders:add_to_cart' product.id %}" method="post" class=" col-md-2">
        {% csrf_token %}
        {{ form.as_table }}
        <input type="submit" value="Add To Cart" class="btn btn-danger">
    </form>

    <!-- Scripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js" charset="utf-8"></script>
    <script src="{% static 'js/product_detail.js' %}" charset="utf-8"></script>
  {% endblock %}

products/templates/products/products_list.html
{% extends 'base.html' %}

{% block content %}
<br>
<a href="{% url 'products:products_list' %}" class="btn btn-danger"><b>All</b></a>
{% for category in categories %}
<div class="btn-group">
      <a href="{% url 'products:category' category.slug %}" class="btn btn-danger"><b>{{ category.name }}</b></a>
      <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
        <span class="visually-hidden">Toggle Dropdown</span>
      </button>

      <ul class="dropdown-menu">
        {% for sub in category.category.all %}
            <li><a class="dropdown-item" href="{{ sub.get_absolute_url }}">{{ sub.name }}</a></li>
        {% endfor %}
      </ul>
</div>
{% endfor %}<br><br>
{% for product in products %}
         <div class="col-lg-3 col-md-6 special-grid best-seller " style="display: inline-block;">
                    <div class="products-single fix">
                        <div class="box-img-hover">
                            <div class="type-lb">
                                <p class="sale">Sale</p>
                            </div>
                            <img src="{{ product.image.url }}" class="img-fluid" alt="Image">
                            <div class="mask-icon">
                                <ul>
                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="View"><i class="fas fa-eye"></i></a></li>
                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="Compare"><i class="fas fa-sync-alt"></i></a></li>
                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="Add to Wishlist"><i class="far fa-heart"></i></a></li>
                                </ul>
                                <a class="cart" href="{% url 'products:detail' product.id product.slug %}">Add to Cart</a>
                            </div>
                        </div>
                        <div class="why-text">
                            <h4>{{ product.name }}</h4>
                            <h5> ${{ product.price }}</h5>
                        </div>
                    </div>
                </div>
    <!-- End Products  -->
{% endfor %}
<br><br>


{% endblock %}